<template>
  <main class="min-h-screen px-6 py-28">
    <div class="mx-auto max-w-4xl space-y-10">
      <header class="space-y-3">
        <h1 class="page-title text-4xl font-bold md:text-5xl">Privacy Policy</h1>
        <p class="text-body"><strong>Last updated:</strong> June 17, 2025</p>
      </header>

      <section class="space-y-4">
        <p class="text-body">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p class="text-body">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Legally responsible acc. to §55 RStV (European Union) and §5 Telemediengesetz (Germany):</h2>
        <div class="text-body">
          <p>Shenpai Productions</p>
          <p>c/o Block Services</p>
          <p>Stuttgarter Str. 106</p>
          <p>70736 Fellbach</p>
        </div>
        <p class="text-body">
          Email:
          <a href="mailto:shenpai@dmbmgmt.com" class="link">shenpai@dmbmgmt.com</a>
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Interpretation and Definitions</h2>

        <h3 class="subsection-title">Interpretation</h3>
        <p class="text-body">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 class="subsection-title">Definitions</h3>
        <p class="text-body">For the purposes of this Privacy Policy:</p>

        <div class="space-y-3 text-body">
          <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
          <p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
          <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
          <p><strong>Country</strong> refers to: Hessen, Germany.</p>
          <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
          <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
          <p><strong>Service</strong> refers to the Website.</p>
          <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
          <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself, for example, the duration of a page visit.</p>
          <p><strong>Website</strong> refers to Birdhaven, accessible from <a href="https://www.birdhavencomic.com/" target="_blank" rel="noopener noreferrer" class="link">https://www.birdhavencomic.com/</a>.</p>
          <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
        </div>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Collecting and Using Your Personal Data</h2>

        <h3 class="subsection-title">Types of Data Collected</h3>

        <h4 class="mini-title">Personal Data</h4>
        <p class="text-body">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.
        </p>
        <p class="text-body">Personally identifiable information may include, but is not limited to:</p>
        <ul class="list-body">
          <li>Email address</li>
          <li>Usage Data</li>
        </ul>

        <h4 class="mini-title">Usage Data</h4>
        <p class="text-body">Usage Data is collected automatically when using the Service.</p>
        <p class="text-body">
          Usage Data may include information such as Your Device's Internet Protocol address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p class="text-body">
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        </p>
        <p class="text-body">
          We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Tracking Technologies and Cookies</h2>

        <p class="text-body">
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
        </p>
        <p class="text-body">The technologies We use may include:</p>

        <div class="space-y-3 text-body">
          <p><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>
          <p><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons, also referred to as clear gifs, pixel tags, and single-pixel gifs, that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</p>
        </div>

        <p class="text-body">
          Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
        </p>

        <p class="text-body">We use both Session and Persistent Cookies for the purposes set out below:</p>

        <div class="space-y-4 text-body">
          <div>
            <p><strong>Necessary / Essential Cookies</strong></p>
            <p>Type: Session Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</p>
          </div>

          <div>
            <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
            <p>Type: Persistent Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
          </div>

          <div>
            <p><strong>Functionality Cookies</strong></p>
            <p>Type: Persistent Cookies</p>
            <p>Administered by: Us</p>
            <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</p>
          </div>
        </div>

        <p class="text-body">
          For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Use of Your Personal Data</h2>
        <p class="text-body">The Company may use Personal Data for the following purposes:</p>
        <ul class="list-body">
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage Your Account, including Your registration as a user of the Service.</li>
          <li>For the performance of a contract.</li>
          <li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
          <li>To provide You with news, special offers and general information unless You have opted not to receive such information.</li>
          <li>To manage Your requests.</li>
          <li>For business transfers.</li>
          <li>For other purposes such as data analysis, usage trends, and improving the Service.</li>
        </ul>

        <p class="text-body">We may share Your personal information in the following situations:</p>
        <ul class="list-body">
          <li>With Service Providers.</li>
          <li>For business transfers.</li>
          <li>With Affiliates.</li>
          <li>With business partners.</li>
          <li>With other users where public interaction occurs.</li>
          <li>With Your consent.</li>
        </ul>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Retention of Your Personal Data</h2>
        <p class="text-body">
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. The Company will also retain Usage Data for internal analysis purposes, except where longer retention is legally required or necessary for security and functionality.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Transfer of Your Personal Data</h2>
        <p class="text-body">
          Your information, including Personal Data, may be processed at the Company's operating offices and in other places where the parties involved in the processing are located. This may mean transfer to computers located outside Your jurisdiction. By submitting such information, You agree to that transfer.
        </p>
        <p class="text-body">
          The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Delete Your Personal Data</h2>
        <p class="text-body">
          You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
        </p>
        <p class="text-body">
          You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information.
        </p>
        <p class="text-body">
          You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
        </p>
        <p class="text-body">
          Please note that We may need to retain certain information when We have a legal obligation or lawful basis to do so.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Disclosure of Your Personal Data</h2>

        <h3 class="subsection-title">Business Transactions</h3>
        <p class="text-body">
          If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
        </p>

        <h3 class="subsection-title">Law enforcement</h3>
        <p class="text-body">
          Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.
        </p>

        <h3 class="subsection-title">Other legal requirements</h3>
        <p class="text-body">
          The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
        </p>
        <ul class="list-body">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Security of Your Personal Data</h2>
        <p class="text-body">
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, and no method of electronic storage, is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Children's Privacy</h2>
        <p class="text-body">
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
        </p>
        <p class="text-body">
          If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information.
        </p>
        <p class="text-body">
          If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Links to Other Websites</h2>
        <p class="text-body">
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
        </p>
        <p class="text-body">
          We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Changes to this Privacy Policy</h2>
        <p class="text-body">
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </p>
        <p class="text-body">
          We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
        </p>
        <p class="text-body">
          You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>
      </section>

      <section class="space-y-4">
        <h2 class="section-title">Contact Us</h2>
        <p class="text-body">If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul class="list-body">
          <li>
            By email:
            <a href="mailto:vero.larue@hotmail.de" class="link">vero.larue@hotmail.de</a>
          </li>
          <li>
            By visiting this page on our website:
            <a href="https://www.birdhavencomic.com/legal" target="_blank" rel="noopener noreferrer" class="link">
              https://www.birdhavencomic.com/legal
            </a>
          </li>
        </ul>
      </section>
    </div>
  </main>
</template>

<script setup>
</script>

<style scoped>
.page-title {
  color: var(--text-main);
}

.section-title {
  color: var(--text-main);
  font-size: 1.5rem;
  font-weight: 600;
}

.subsection-title {
  color: var(--text-main);
  font-size: 1.1rem;
  font-weight: 600;
}

.mini-title {
  color: var(--text-main);
  font-size: 1rem;
  font-weight: 600;
}

.text-body {
  color: var(--text-soft);
  line-height: 1.7;
}

.list-body {
  color: var(--text-soft);
  line-height: 1.7;
  padding-left: 1.25rem;
  list-style-type: disc;
}

.link {
  color: var(--text-main);
  text-decoration: underline;
}

.link:hover {
  opacity: 0.7;
}
</style>